apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-db
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/simonangel-fong/secure-aks.git
    targetRevision: master
    path: argocd/manifests/secret-db
  destination:
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
